//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DATPHONG_CHITIET
    {
        public int IDDP { get; set; }
        public int IDPHONG { get; set; }
        public Nullable<int> SONGUOI { get; set; }
        public Nullable<double> DONGIA { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public Nullable<int> SONGAY { get; set; }
        public Nullable<System.DateTime> NGAYNHAN { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
    
        public virtual tb_DatPhong tb_DatPhong { get; set; }
        public virtual tb_Phong tb_Phong { get; set; }
    }
}
