//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_THANHTOAN
    {
        public int IDTT { get; set; }
        public Nullable<System.DateTime> NGAYTT { get; set; }
        public Nullable<double> TONGTIENTT { get; set; }
        public Nullable<bool> TRANGTHAITT { get; set; }
        public Nullable<int> IDDP { get; set; }
        public Nullable<int> IDPHONG { get; set; }
        public Nullable<int> UID { get; set; }
    
        public virtual tb_DatPhong tb_DatPhong { get; set; }
        public virtual tb_Phong tb_Phong { get; set; }
        public virtual tb_Users tb_Users { get; set; }
    }
}
